---
abstract: 'be like TOBYINK and use these Moose stuffz'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Task::BeLike::TOBYINK::Moose
name: Task-BeLike-TOBYINK-Moose
no_index:
  directory:
    - inc
    - xt
requires:
  Moose: 0
  MooseX::ABCD: 0
  MooseX::ArrayRef: 0
  MooseX::AttributeShortcuts: 0
  MooseX::DeclareX: 0
  MooseX::DeclareX::Keyword::interface: 0
  MooseX::DeclareX::Plugin::abstract: 0
  MooseX::DeclareX::Plugin::singleton: 0
  MooseX::FunkyAttributes: 0
  MooseX::Interface: 0
  MooseX::NonMoose: 0
  MooseX::Traits: 0
  MooseX::Types: 0
  MooseX::Types::Common: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::Perl: 0
  MooseX::Types::URI: 0
  Scalar::Does: 0
  Throwable: 0
  TryCatch: 0
  namespace::sweep: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Task-BeLike-TOBYINK-Moose
  homepage: https://metacpan.org/release/Task-BeLike-TOBYINK-Moose
  license: http://dev.perl.org/licenses/
version: 2012.276
